version: "2"

linters:
  default: standard
  enable:
    - paralleltest
  settings:
    errcheck:
      exclude-functions:
        - (io.Closer).Close
        - (*os.File).Close
        - (*mime/multipart.Part).Close
        - (*mime/multipart.Writer).Close
        - (*mime/multipart.Form).RemoveAll
        - (net/http.ResponseWriter).Write
